version: '3'

services:
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_ENABLE_XDB=true
    ports:
      - 1521:1521
      - 5500:5500